// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLknmPB9Y7WMGZcuE3Uogo44vVbdF9mN8',
    appId: '1:852905012839:web:446c7e189b011c1c21eec2',
    messagingSenderId: '852905012839',
    projectId: 'florida-handbook',
    authDomain: 'florida-handbook.firebaseapp.com',
    storageBucket: 'florida-handbook.firebasestorage.app',
    measurementId: 'G-Z8SS68KPGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_NYk9IaNgpMqnLvGtUoh8nJXaqNXu2E4',
    appId: '1:852905012839:android:857fe40946ad18c621eec2',
    messagingSenderId: '852905012839',
    projectId: 'florida-handbook',
    storageBucket: 'florida-handbook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByH3eiflgd4oLySAzRSZLKxGd8B_xUvCc',
    appId: '1:852905012839:ios:6778262dfad2ad3c21eec2',
    messagingSenderId: '852905012839',
    projectId: 'florida-handbook',
    storageBucket: 'florida-handbook.firebasestorage.app',
    iosClientId: '852905012839-gem716tfi613825sgj6uh8dn7d495ek2.apps.googleusercontent.com',
    iosBundleId: 'com.example.floridaHandbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByH3eiflgd4oLySAzRSZLKxGd8B_xUvCc',
    appId: '1:852905012839:ios:6778262dfad2ad3c21eec2',
    messagingSenderId: '852905012839',
    projectId: 'florida-handbook',
    storageBucket: 'florida-handbook.firebasestorage.app',
    iosClientId: '852905012839-gem716tfi613825sgj6uh8dn7d495ek2.apps.googleusercontent.com',
    iosBundleId: 'com.example.floridaHandbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLknmPB9Y7WMGZcuE3Uogo44vVbdF9mN8',
    appId: '1:852905012839:web:446c7e189b011c1c21eec2',
    messagingSenderId: '852905012839',
    projectId: 'florida-handbook',
    authDomain: 'florida-handbook.firebaseapp.com',
    storageBucket: 'florida-handbook.firebasestorage.app',
    measurementId: 'G-Z8SS68KPGP',
  );

}