name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたら実行

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu環境で実行

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v3  # リポジトリのコードを取得

      - name: Flutterのセットアップ
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # 最新の安定版Flutterを使用

      - name: 依存関係のインストール
        run: flutter pub get  # pubspec.yaml の依存関係を解決

      - name: Flutter Webアプリのビルド
        run: flutter build web --release  # 本番用のビルド

      - name: GitHub Pagesへのデプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHubトークンで認証
          publish_dir: ./build/web  # ビルドされたWebアプリのディレクトリ
          publish_branch: main  # mainブランチにデプロイ
